import json
import os
import re
import fugashi
import jaconv
from functools import lru_cache

# Initialize Fugashi with UniDic
tagger = fugashi.Tagger()

@lru_cache(maxsize=10000)
def generate_ruby(text):
    if not text:
        return ""
        
    out = []
    
    # Process each token generated by the context-aware MeCab tagger
    for word in tagger(text):
        orig = word.surface
        
        # If there's no Kanji in the surface, no furigana needed
        if not re.search(r'[\u4e00-\u9fff]', orig):
            out.append(orig)
            continue
            
        # Get the parsed pronunciation/kana from UniDic
        kana = getattr(word.feature, 'kana', None)
        if not kana:
            out.append(orig)
            continue
            
        # UniDic kana is in Katakana, so convert to Hiragana
        hira = jaconv.kata2hira(kana)
        
        orig_len = len(orig)
        hira_len = len(hira)
        
        # Suffix matching logic for Okurigana
        suffix = ""
        i = 1
        while i <= orig_len and i <= hira_len:
            if orig[-i] == hira[-i]:
                suffix = orig[-i] + suffix
                i += 1
            else:
                break
                
        # Prefix matching logic (for honorifics, etc.)
        prefix = ""
        j = 0
        hira_start = 0
        orig_start = 0
        while j < (orig_len - len(suffix)) and j < (hira_len - len(suffix)):
            if orig[j] == hira[j]:
                prefix += orig[j]
                j += 1
                hira_start += 1
                orig_start += 1
            else:
                break
                
        kanji_part = orig[orig_start : orig_len - len(suffix)]
        ruby_part = hira[hira_start : hira_len - len(suffix)]
        
        if kanji_part and ruby_part and kanji_part != ruby_part:
            out.append(f"{prefix}{kanji_part}[{ruby_part}]{suffix}")
        else:
            out.append(orig)
            
    return "".join(out)

def main():
    file_path = 'raw_grammar_data.json'
    if not os.path.exists(file_path):
        print(f"File {file_path} not found.")
        return
        
    with open(file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
        
    count = 0
    print("Starting exact contextual Ruby generation via Fugashi + UniDic...")
    
    for item in data:
        for ex in item.get('examples', []):
            sentence = ex.get('japanese', '')
            if sentence:
                ex['japanese_ruby'] = generate_ruby(sentence)
                count += 1
                
    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        
    print(f"Success! Updated {count} Ruby annotations using the industry-leading Fugashi analyzer.")

if __name__ == "__main__":
    main()
